.install-qt-webview: &install-qt-webview
  before_script:
    - sudo pacman -Ssy qt5-webview -noprogressbar --noconfirm

job-archlinux-latest-ninja-clang:
  tags: [ "docker-archlinux-latest" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION
  except:
    refs:
      - schedules
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
  extends: .job-linux-desktop
  <<: *install-qt-webview

#################################################
#               Nightly
#################################################

job-archlinux-latest-makefile-gcc:
  tags: [ "docker-archlinux-latest" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION
  only:
    variables:
      - $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++
  extends: .job-linux-desktop
  <<: *install-qt-webview


job-archlinux-latest-makefile-clang:
  tags: [ "docker-archlinux-latest" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION
  only:
    variables:
      - $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++
  extends: .job-linux-desktop
  <<: *install-qt-webview


job-archlinux-latest-ninja-gcc:
  tags: [ "docker-archlinux-latest" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION
  only:
    variables:
      - $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
  extends: .job-linux-desktop
  <<: *install-qt-webview

job-archlinux-latest-ninja-gcc-novideo:
  tags: [ "docker-archlinux-latest" ]
  only:
    variables:
      - $NIGHTLY_MASTER
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO
  extends: job-archlinux-latest-ninja-gcc
  <<: *install-qt-webview

job-archlinux-latest-ninja-clang-novideo:
  tags: [ "docker-archlinux-latest" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION
  only:
    variables:
      - $NIGHTLY_MASTER
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
  extends: .job-linux-desktop
  <<: *install-qt-webview

#################################################
# Package - Nightly
#################################################

#job-archlinux-latest-makefile-clang-package:
#  stage: package
#  tags: [ "docker-archlinux-latest" ]
#  only:
#     variables:
#       - $NIGHTLY_MASTER
#       - $DEPLOY_LINUX
#  variables:
#    CMAKE_OPTIONS: -DENABLE_APP_PACKAGING=YES
#  extends: job-archlinux-latest-makefile-clang
#  artifacts:
#    paths:
#      - build/OUTPUT/Packages/Linphone*.AppImage
#    expire_in: 1 week
#
#################################################
# Deploy - Nightly
#################################################

#job-archlinux-latest-makefile-clang-deploy:
#  stage: deploy
#  tags: [ "docker-archlinux-latest" ]
#  dependencies:
#    - job-archlinux-latest-makefile-clang-package
#  only:
#     variables:
#       - $NIGHTLY_MASTER
#       - $DEPLOY_LINUX
#  script:
#    - scp build/OUTPUT/Packages/Linphone*.AppImage $DEPLOY_SERVER:$APPIMAGE_UPLOAD_DIRECTORY/
