#################################################
# BUILD
#################################################

.job-linux-desktop:

  stage: build
  extends: .linux-prepare

  script:
    - export CC=$CC
    - export CXX=$CXX
    - mkdir -p build-desktop/OUTPUT
    - export 
    - echo $CMAKE_GENERATOR
    - echo $DEFAULT_LINUX_CMAKE_OPTIONS
    - echo $CMAKE_OPTIONS
    - echo $CMAKE_SANITIZER_OPTIONS
# SDK Building
    - mkdir -p linphone-sdk/build-sdk
    - cd linphone-sdk/build-sdk
    - cmake .. -G "$CMAKE_GENERATOR" -DLINPHONESDK_PLATFORM=Desktop $DEFAULT_LINUX_CMAKE_OPTIONS $CMAKE_OPTIONS $SCHEDULE_CMAKE_OPTIONS $CMAKE_SANITIZER_OPTIONS 
    - cmake --build . --target sdk -- $ADDITIONAL_BUILD_OPTIONS
    - cd ../../submodules/externals/minizip    
# Minizip submodule Building
    - mkdir -p build-minizip
    - cd build-minizip
    - cmake .. -G "$CMAKE_GENERATOR" $DEFAULT_LINUX_CMAKE_OPTIONS $CMAKE_OPTIONS $SCHEDULE_CMAKE_OPTIONS $CMAKE_SANITIZER_OPTIONS -DCMAKE_INSTALL_PREFIX=OUTPUT
    - cmake --build . --target all -- $ADDITIONAL_BUILD_OPTIONS
    - cmake --build . --target install -- $ADDITIONAL_BUILD_OPTIONS
# Desktop Building
    - cd ../../../../build-desktop
    - cmake .. -G "$CMAKE_GENERATOR" $DEFAULT_LINUX_CMAKE_OPTIONS $CMAKE_OPTIONS $SCHEDULE_CMAKE_OPTIONS $CMAKE_SANITIZER_OPTIONS -DCMAKE_INSTALL_PREFIX=OUTPUT -DCMAKE_PREFIX_PATH="linphone-sdk/build-sdk/linphone-sdk/desktop;submodules/externals/minizip/build-minizip/OUTPUT"
    - cmake --build . --target all -- $ADDITIONAL_BUILD_OPTIONS
    - cmake --build . --target install -- $ADDITIONAL_BUILD_OPTIONS

  artifacts:
    paths:
      - build-desktop/OUTPUT
      - linphone-sdk/build-sdk/linphone-sdk/desktop
      - submodules/externals/minizip/build-minizip/OUTPUT
    expire_in: 1 week

